dataset:
  data_length: null  # null = full dataset
  target_column: loan_paid_back
  test_size_1: 0.3 #70:30 train test split
  test_size_2: 0.5 #50:50 split between 30% of test set as test and validation
  stratify: true
  random_state: 11

pytorch:
  batch_size: 128
  epoch: 10
  learning_rate: 0.0001
  weight_decay: 0.00001
  model_input_dim: 11
  hidden_layers: [64, 32, 16]
  dropout: 0.1

mlflow:
  tracking_uri: http://localhost:5000
  experiment_name: LoanPayback
  model_name: LoanPayback
  model_uri: models:/LoanPayback/Production

inference:
  prediction_threshold: 0.5
